import sys

from lib import two_factor

if __name__ == "__main__":
    print("Generating two-factor authentication code...")
    secret_token = two_factor.generate_secret_token()
    print("Your two-factor authentication code is: \n\n{}\n".format(secret_token))
    print("You should type this into your authenticator app.")
    print(
        "If you don't have an authenticator app, you can use Google"
        " Authenticator or Authy."
    )
    print(
        "Make sure you copy this code into your config.py file in the"
        ' "approved_users" section too.'
    )

    print("\n\n")

    code = input(
        "Please enter your two-factor authentication code generated by"
        " your authenticator app:"
    )
    verified = two_factor.verify_otp_code("user", code, secret_token)
    if verified:
        print("Two-factor authentication code verified.")
    else:
        print("Two-factor authentication code invalid.", file=sys.stderr)
