import sys

from lib import two_factor


def main(config_file="config.json", interactive=True):
    # Don't do anything with the config file

    secret_token = two_factor.generate_secret_token()
    print("Your two-factor authentication key is: \n\n{}\n".format(secret_token))
    print(
        "You should type this into your authenticator app (token length of"
        " 6, if your app asks)."
    )
    print(
        "If you don't have an authenticator app, you can use Google"
        " Authenticator or Authy."
    )
    print(
        "Make sure you copy this code into your config.py file in the"
        ' "approved_users" section too.'
    )

    print("\n\n")

    verified = False
    while not verified:
        code = input(
            "Please enter the two-factor authentication code generated by"
            " your authenticator app (numbers only, no spaces): "
        )
        verified = two_factor.verify_code_only(code, secret_token)
        if verified:
            print("Two-factor authentication code verified.")
        else:
            print("Two-factor authentication code invalid.", file=sys.stderr)
            print("Try re-entering the key into your authenticator app.")

    print("\n\n")
    print(
        "Two-factor authentication setup complete.\nPlease enter the key {}"
        " into the config file along with the email address of any associated"
        " users.".format(secret_token)
    )


if __name__ == "__main__":
    main(config_file="config.json", interactive=True)
